### ISSUE TITLE
PowerUps!

### ISSUE THREAD

**Issue by andyriffic** [andyriffic/CNB#13]
![](https://media.giphy.com/media/NSqSKwOH4cUa0ZHoNA/giphy.gif)

# Overview

A PowerUp would be something a team can play before they select their move.
Based on the outcome of the game, the PowerUp can affect the result.

# Examples of PowerUps

Possible PowerUps could be:

| PowerUp | Description |
|---|---|
| Double Points | If you win the game you receive double points (including double bonus points) |
| Reverse | The result of the game is reversed (winner = loser) |
| Points Swap | If you win then you swap scores with the other team  |
| Points Stealer | If you win then you take a point from the other team (either as well as the point you would've won or as the only point) |

# How you get PowerUps

PowerUps would be awarded after each game either randomly or under certain conditions.
e.g., Once you reach X points, If you are more than X points behind etc.

# PowerUp State

Could save the state of the PowerUps each team has in the Counter repository. If each Team+PowerUp had it's own counter then we can +/- the counter to know how many PowerUps each team has.

The Client Selection Screen would be responsible for selecting a PowerUp to be used when the player makes their selection.

In `SocketsConnection.js` we will handle the 'onGameFinished' event to apply the outcome of any PowerUps that were played. This is the same place we update the scores.

# Server State

We would need to send an optional PowerUp attribute to the server when a user makes a selection. That way it will be available on the spectator screen.

**Comment by mike055** [comment]
I think the awarding of power ups, storing of them and selecting them seem to make sense.

I think the UI flow of applying power ups in a non confusing way needs to thought about more.

Are we going to run the game as normal so people think they know what happened and then BAM! the power up sequence runs and changes the results/scores?

**Comment by mike055** [comment]
Also what if both players apply a power up, what happens then? Is there a priority or precedence to them, it is like another game of rock/paper/scissors just in applying the winning power up.

**Comment by andyriffic** [comment]
> Are we going to run the game as normal so people think they know what happened and then BAM! the power up sequence runs and changes the results/scores?

I was thinking that you would see on the spectator screen that a team has chosen to play a power up...whether it would tell you what the power up was or it was a 'mystery' could be up for A/B testing.

> Also what if both players apply a power up, what happens then? Is there a priority or precedence to them, it is like another game of rock/paper/scissors just in applying the winning power up.

I was thinking the PowerUp should only apply if you win so that takes care of the ordering. But if we get more fancy PowerUps in the future we could think of a system to apply them

**Comment by andyriffic** [comment]
Also to begin with, having PowerUps that only change the scoring will be the simplest implementation so would start with something simple.
